apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: medical-app
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/medical_examination_booking"
  KEYCLOAK_ISSUER_URI: "http://keycloak:8080/realms/medicalRealm"