apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: medical-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bjovanceva/medical-backend:latest
          ports:
            - containerPort: 9091
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: medical-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bjovanceva/medical-frontend:latest
          ports:
            - containerPort: 80
