name: CI/CD Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/medical-backend:latest ./medical_examination_booking_backend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/medical-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/medical-frontend:latest ./medical_examination_booking_frontend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/medical-frontend:latest